# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(docs): "
    groups:
      website:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(ci): "
    groups:
      github-actions:
        patterns:
          - "*"
